---
title: "FInal Project"
author: "Mari Jones"
date: "12/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(janitor)
library(readxl)
library(readr)
library(ggplot2)
library(cowplot)
```

```{r}
juvie_reports <- read_excel("juvenile_data.xlsx", skip = 10) %>%
  clean_names() %>%
  filter(!is.na("NA"))

names(juvie_reports) <- juvie_reports[1,]
juvie_reports <- juvie_reports[-(1:3), -2]
```

```{r}
national <- read_excel("nat_demographic_data.xlsx", skip = 3) %>%
  clean_names()

national <- national[-(34:39),]

national$year <- as.numeric(national$year)
```

```{r}
youth_pop <- read_excel("us_youth_pop.xlsx", skip = 4) %>%
  clean_names()
```

```{r}
women <- read_excel("women_in_jail.xlsx", skip = 2) %>%
  clean_names()
```

```{r}
p1 <- ggplot(national, aes(x = year, y = total, color = "total")) + geom_point(aes(x = year, y = black, color = "black"))  + scale_x_continuous(breaks = seq(1985, 2020, by = 5)) + ylim(min = 0, max = 2000000) + geom_point(aes(x = year, y = white, color = "white")) + geom_point(aes(x = year, y = american_indian, color = "american_indian")) + geom_point(aes(x = year, y = asian_nhpi, color = "asian_nphi")) + geom_point(aes(x = year, y = hispanic, color = "hispanic")) + geom_point(aes(x = year, y = total, color = "total")) +
  theme_cowplot()

p2 <- ggplot(national, aes(x = year, y = total)) + geom_point(aes(x = year, y = female, color = "female")) + geom_point(aes(x = year, y = male, color = "male")) +
  theme_cowplot()

plot_grid(p2, p1,nrow = 1, 
          labels = c('Gender Makeup of Incarcerated Youth', 'Racial Makeup of Incarcerated Youth'),
          label_size =10)

```

```{r}
moms <- read_excel("moms.xlsx", skip = 2) %>%
  clean_names()
moms1 <- as.data.frame(moms)
moms <- as.data.frame(moms)
for(i in 2:nrow(moms1)){
    moms1[i-1,2:4] = moms1[i-1,2:4]*moms1[nrow(moms1), 2:4]
}

momsvert <- matrix(NA, ncol = 4)

for(i in 1:(nrow(moms1)-1)){
     vect = c(moms1[i, 1], moms1[i, 2], moms[i, 2], "total")
     momsvert <- rbind(momsvert, vect)
     vect = c(moms1[i, 1], moms1[i, 3], moms[i,3], "men")
     momsvert <- rbind(momsvert, vect)
     vect = c(moms1[i, 1], moms1[i, 4], moms[i, 4], "women")
     momsvert <- rbind(momsvert, vect)      
}
colnames(momsvert) <- c("type", "count", "proportion", "class")

momsvert <- momsvert[-1, ]
momsvert <- as.data.frame(momsvert)
ggplot(data = momsvert, aes(x = type, y = count, fill = class)) + geom_bar(stat = "identity", position = position_dodge()) + ggtitle("Parental Interaction with Children Before & During Incarceration") + ylab("Number of Inmates with Children") + xlab("Type of Interaction")

p3 <- ggplot(data = momsvert, aes(x = type, y = proportion, fill = class)) + geom_bar(stat = "identity", position = position_dodge()) + ggtitle("Parental Interaction with Children Before & During Incarceration") + ylab("Percentage of Inmates with Children") + xlab("Type of Interaction") +
  theme_cowplot()

p4 <- ggplot(women, aes(x = year, y = female)) + geom_line(color = "red") + ggtitle("Changes in Female Incarceration Population (2007-2017)") + ylab("Number of Women") + xlab("Year") +
  theme_cowplot()

plot_grid(p4, p3, nrow = 1, 
          labels = c('Incarcerated Adults with Children', 'Changes in Female Incarceration Population (2007-2017)'),
          label_size =10)
```

```{r}
women <- read_excel("women_in_jail.xlsx", skip = 2) %>%
  clean_names()

ggplot(women, aes(x = year, y = female)) + geom_line(color = "red") + ggtitle("Changes in Female Incarceration Population (2007-2017)") + ylab("Number of Women") + xlab("Year")
```

